graph TD
    %% Main Spivak Family Branch
    andrew_spivak["Andrew Spivak (deceased)"] --- olga_spivak_sr["Olga Spivak Sr. (deceased)"]
    andrew_spivak --> lydia_spivak["Lydia Spivak (1939-2015)"]
    andrew_spivak --> nicholas_spivak["Nicholas Spivak (1932-2014)"]
    andrew_spivak --> ivan_spivak["Ivan Spivak (deceased)"]
    andrew_spivak --> dmitro_spivak["Dmitro/James Spivak (deceased)"]
    andrew_spivak --> john_spivak["John Spivak (d. 2011)"]
    
    %% Nicholas Spivak branch
    nicholas_spivak --- olga_schidowka["Olga Schidowka"]
    nicholas_spivak --> walter_spivak["Walter Spivak"]
    nicholas_spivak --> james_spivak["James Spivak (d. 1983)"]
    
    walter_spivak --- sue_spivak["Sue Spivak"]
    walter_spivak --> katie_spivak["Katie Spivak"]
    walter_spivak --> cole_spivak["Cole Spivak"]
    walter_spivak --> claudia_spivak["Claudia Spivak"]
    
    james_spivak --> jim_spivak["Jim Spivak"]
    james_spivak --> michael_spivak["Michael Spivak"]
    
    jim_spivak --- carol_spivak["Carol Spivak"]
    jim_spivak --> aiden_spivak["Aiden Spivak"]
    jim_spivak --> ben_spivak["Ben Spivak"]
    jim_spivak --> evelyn_spivak["Evelyn Spivak"]
    
    michael_spivak --- krysten_spivak["Krysten Spivak"]
    
    %% John Spivak branch
    john_spivak --- carol_anne["Carol Anne"]
    john_spivak -.-> joey["Joey (Step-child)"]
    john_spivak -.-> valerie["Valerie (Step-child)"]
    
    %% Lydia Spivak branch and Schewtschenko family
    lydia_spivak --- john_schewtschenko["John Schewtschenko (1935-2018)"]
    lydia_spivak --> fred_schewtschenko["Fred Schewtschenko"]
    lydia_spivak --> olga_schewtschenko["Olga Schewtschenko"]
    lydia_spivak --> andrew_schewtschenko["Andrew Schewtschenko"]
    lydia_spivak --> paul_schewtschenko["Paul Schewtschenko"]
    
    fred_schewtschenko --- oksana_schewtschenko["Oksana Schewtschenko"]
    
    olga_schewtschenko --- paul_lysyk["Paul Lysyk"]
    olga_schewtschenko --> matthew_lysyk["Matthew Lysyk"]
    olga_schewtschenko --> andrew_lysyk["Andrew Lysyk"]
    
    matthew_lysyk --- melissa_lysyk["Melissa Lysyk"]
    matthew_lysyk --> henry_lysyk["Henry Lysyk"]
    matthew_lysyk --> ziggy_lysyk["Ziggy Lysyk"]
    
    andrew_schewtschenko --> michael_schewtschenko["Michael Schewtschenko"]
    
    %% Schidowka family connections
    olga_schidowka --> nicholas_schidowka["Nicholas John Schidowka (1942-2019)"]
    olga_schidowka --> alex_schidowka["Alex Schidowka"]
    
    nicholas_schidowka --- vera_schidowka["Vera Schidowka"]
    alex_schidowka --- helen_schidowka["Helen Schidowka"]
    
    %% Bloschinsky and Koschman families
    alexander_bloschinsky["Alexander Bloschinsky (1928-2011)"] --- helena_koschman["Helena (1933-2016)"]
    alexander_bloschinsky -.-> helen_sawrantschuk["Helen Sawrantschuk"]
    
    alexander_bloschinsky --> mary_bloschinsky["Mary Bloschinsky"]
    alexander_bloschinsky --> nadine_bloschinsky["Nadine Bloschinsky"]
    alexander_bloschinsky --> george_bloschinsky["George Bloschinsky"]
    alexander_bloschinsky --> alex_bloschinsky_jr["Alex Bloschinsky Jr."]
    alexander_bloschinsky --> olena_bloschinsky["Olena Bloschinsky"]
    
    helena_koschman --- nicolas_koschman["Nicolas Koschman (1927-2022)"]
    
    nicolas_koschman --- first_wife_koschman["First Wife (deceased)"]
    nicolas_koschman --> stephanie_koschman["Stephanie Koschman"]
    nicolas_koschman --> christine_koschman["Christine Koschman"]
    
    nicolas_koschman --- peter_koschmann["Peter Koschmann (Brother)"]
    nicolas_koschman --- dimitri_koschman["Dimitri Koschman (Brother, deceased)"]
    nicolas_koschman --- walter_koschman["Walter Koschman (Brother, deceased)"]
    
    %% Extended connections for Bloschinsky family
    mary_bloschinsky --- egon_schoenewolf["Egon Schoenewolf"]
    mary_bloschinsky --> greg_schoenewolf["Greg Schoenewolf"]
    
    nadine_bloschinsky --- todd_wakely["Todd Wakely"]
    nadine_bloschinsky --> shannon_wakely["Shannon Wakely"]
    
    george_bloschinsky --- jennifer_bloschinsky["Jennifer Bloschinsky"]
    george_bloschinsky --> emma_bloschinsky["Emma Bloschinsky"]
    george_bloschinsky --> logan_bloschinsky["Logan Bloschinsky"]
    
    alex_bloschinsky_jr --- gail_bloschinsky["Gail Bloschinsky"]
    alex_bloschinsky_jr --> austin_bloschinsky["Austin Bloschinsky"]
    alex_bloschinsky_jr --> connor_bloschinsky["Connor Bloschinsky"]
    
    olena_bloschinsky --- paul_schewtschenko
    olena_bloschinsky --> slavko_schewtschenko["Slavko Schewtschenko"]
    olena_bloschinsky --> taisa_schewtschenko["Taisa Schewtschenko"]
    olena_bloschinsky --> ala_schewtschenko["Ala Schewtschenko"]
    olena_bloschinsky --> aj_schewtschenko["AJ Schewtschenko"]
    
    %% Tischenko family
    stefan_tischenko["Stefan Tischenko (1921-2014)"] --- maria_tischenko["Maria Tischenko (d. 2001)"]
    stefan_tischenko --> infant_son["Infant Son (deceased)"]
    stefan_tischenko --> lily_hopcroft["Lily Hopcroft"]
    stefan_tischenko --> anne_salmon["Anne Salmon"]
    stefan_tischenko --> tony_tischenko["Tony Tischenko"]
    
    fedosia_tischenko["Fedosia Tischenko (deceased)"] --- ivan_tischenko["Ivan Tischenko (deceased)"]
    fedosia_tischenko --> stefan_tischenko
    fedosia_tischenko --> antone_tischenko["Antone Tischenko (deceased)"]
    fedosia_tischenko --> mykola_tischenko["Mykola Tischenko"]
    
    lily_hopcroft --- grant_hopcroft["Grant Hopcroft"]
    lily_hopcroft --> lara_hopcroft["Lara Hopcroft"]
    lily_hopcroft --> lisa_hopcroft["Lisa Hopcroft"]
    lily_hopcroft --> christina_hopcroft["Christina Hopcroft"]
    
    anne_salmon --- wayne_salmon["Wayne Salmon"]
    
    tony_tischenko --> eli_tischenko["Eli Tischenko"]
    eli_tischenko --- sasha_tischenko["Sasha Tischenko"]
    
    %% Huytan family
    mykhailo_huytan["Mykhailo Huytan (deceased)"] --- magdelyna_huytan["Magdelyna Huytan (deceased)"]
    mykhailo_huytan --> orest_huytan["Orest Huytan (1926-2012)"]
    
    orest_huytan --- tamara_huytan["Tamara Huytan"]
    orest_huytan --> konstantin_huytan["Konstantin Huytan"]
    orest_huytan --> paul_huytan["Paul Huytan"]
    
    konstantin_huytan --- lesia_maruschak["Lesia Maruschak"]
    konstantin_huytan --> arkady_huytan["Arkady Huytan"]
    konstantin_huytan --> nadia_huytan["Nadia Huytan"]
    
    %% Danylchenko family
    gregory_danylchenko_sr["Gregory Danylchenko Sr. (deceased)"] --- maria_danylchenko["Maria Danylchenko (deceased)"]
    gregory_danylchenko_sr --> ivan_danylchenko["Ivan Danylchenko (1925-2023)"]
    gregory_danylchenko_sr --> nastusia_danylchenko["Nastusia Danylchenko (deceased)"]
    gregory_danylchenko_sr --> gregory_danylchenko_jr["Gregory Danylchenko Jr. (deceased)"]
    
    ivan_danylchenko --- nadia_danylchenko["Nadia Danylchenko"]
    ivan_danylchenko --> gregory_danylchenko_son["Gregory Danylchenko (b. 1953)"]
    ivan_danylchenko --> victor_danylchenko["Victor Danylchenko (b. 1957)"]
    
    gregory_danylchenko_son --- janice_neelands["Janice Neelands"]
    
    victor_danylchenko --- christina_broadbent["Christina Broadbent"]
    victor_danylchenko --> tamara_danylchenko["Tamara Danylchenko"]
    victor_danylchenko --> alexa_danylchenko["Alexa Danylchenko"]
    
    alexa_danylchenko --- derek_foster["Derek Foster"]
    
    %% Legend
    classDef deceased fill:#D3D3D3,stroke:#A9A9A9,color:#333333
    classDef living fill:#E8F5E9,stroke:#81C784,color:#333333
    classDef marriage stroke:#FF69B4,stroke-width:2px
    classDef stepRelation stroke-dasharray: 5 5
    
    %% Apply classes to nodes
    class andrew_spivak,olga_spivak_sr,ivan_spivak,nicholas_spivak,dmitro_spivak,john_spivak,lydia_spivak,james_spivak,john_schewtschenko,alexander_bloschinsky,helena_koschman,nicolas_koschman,first_wife_koschman,dimitri_koschman,walter_koschman,gregory_danylchenko_sr,maria_danylchenko,gregory_danylchenko_jr,nastusia_danylchenko,ivan_danylchenko,fedosia_tischenko,ivan_tischenko,antone_tischenko,maria_tischenko,infant_son,stefan_tischenko,mykhailo_huytan,magdelyna_huytan,orest_huytan deceased;
    
    %% Apply class to step-relations
    class joey,valerie,helen_sawrantschuk stepRelation;
